name: Test binaryen

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        ocaml-compiler:
          - "4.14"
          - "5.02"
          - "5.03"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install conf-mingw-w64-g++-x86_64

#      - run: opam install binaryen-bin
#
#      - run: opam exec -- which wasm-opt.exe
#
#      - run: opam exec -- ldd D:\a\wasm_of_ocaml\wasm_of_ocaml\_opam\bin\wasm-opt.exe

      - run: opam install wasm_of_ocaml-compiler
